# Exported from Render on 2024-04-14T03:18:49Z
services:
- type: web
  name: nyanyanyacat
  runtime: python
  repo: https://github.com/Skype-GitHub/YUKI-GOD
  plan: free
  envVars:
  - key: hcaptcha
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python3 main.py & python3 news.py
version: "1"
